In [59]:
import numpy as np
import pandas as pd

In [60]:
df=pd.read_csv('brain_tumor_dataset.csv')
df

,Patient_ID,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1,73,Male,Malignant,5.375612,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,No,No,No,51.312579,0.111876,No,Positive,Yes
1,2,26,Male,Benign,4.847098,Parietal,Glioblastoma,II,Headache,Headache,Nausea,Yes,Yes,Yes,46.373273,2.165736,Yes,Positive,Yes
2,3,31,Male,Benign,5.588391,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,No,No,No,47.072221,1.884228,No,Negative,No
3,4,29,Male,Malignant,1.436600,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,Yes,No,Yes,51.853634,1.283342,Yes,Negative,No
4,5,54,Female,Benign,2.417506,Parietal,Glioblastoma,I,Headache,Headache,Seizures,No,No,Yes,54.708987,2.069477,No,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,21,Male,Malignant,9.612013,Parietal,Medulloblastoma,III,Seizures,Nausea,Vision Issues,No,No,Yes,58.229662,0.353806,No,Negative,Yes
19996,19997,32,Female,Benign,1.543560,Temporal,Meningioma,III,Headache,Headache,Vision Issues,Yes,Yes,No,77.706856,2.341074,No,Positive,No
19997,19998,57,Female,Benign,3.618634,Temporal,Medulloblastoma,I,Seizures,Vision Issues,Nausea,No,No,Yes,89.543803,2.332881,No,Positive,Yes
19998,19999,68,Male,Malignant,8.519086,Parietal,Glioblastoma,III,Seizures,Headache,Vision Issues,Yes,Yes,Yes,83.306781,2.387202,No,Positive,No
19999,20000,61,Male,Benign,9.716768,Temporal,Medulloblastoma,I,Vision Issues,Seizures,Nausea,No,No,No,47.433468,2.464077,Yes,Negative,Yes

In [61]:
df.head()

,Patient_ID,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1,73,Male,Malignant,5.375612,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,No,No,No,51.312579,0.111876,No,Positive,Yes
1,2,26,Male,Benign,4.847098,Parietal,Glioblastoma,II,Headache,Headache,Nausea,Yes,Yes,Yes,46.373273,2.165736,Yes,Positive,Yes
2,3,31,Male,Benign,5.588391,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,No,No,No,47.072221,1.884228,No,Negative,No
3,4,29,Male,Malignant,1.436600,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,Yes,No,Yes,51.853634,1.283342,Yes,Negative,No
4,5,54,Female,Benign,2.417506,Parietal,Glioblastoma,I,Headache,Headache,Seizures,No,No,Yes,54.708987,2.069477,No,Positive,Yes

In [62]:
df.tail()

,Patient_ID,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
19995,19996,21,Male,Malignant,9.612013,Parietal,Medulloblastoma,III,Seizures,Nausea,Vision Issues,No,No,Yes,58.229662,0.353806,No,Negative,Yes
19996,19997,32,Female,Benign,1.543560,Temporal,Meningioma,III,Headache,Headache,Vision Issues,Yes,Yes,No,77.706856,2.341074,No,Positive,No
19997,19998,57,Female,Benign,3.618634,Temporal,Medulloblastoma,I,Seizures,Vision Issues,Nausea,No,No,Yes,89.543803,2.332881,No,Positive,Yes
19998,19999,68,Male,Malignant,8.519086,Parietal,Glioblastoma,III,Seizures,Headache,Vision Issues,Yes,Yes,Yes,83.306781,2.387202,No,Positive,No
19999,20000,61,Male,Benign,9.716768,Temporal,Medulloblastoma,I,Vision Issues,Seizures,Nausea,No,No,No,47.433468,2.464077,Yes,Negative,Yes

In [63]:
df.dtypes

Patient_ID               int64
Age                      int64
Gender                  object
Tumor_Type              object
Tumor_Size             float64
Location                object
Histology               object
Stage                   object
Symptom_1               object
Symptom_2               object
Symptom_3               object
Radiation_Treatment     object
Surgery_Performed       object
Chemotherapy            object
Survival_Rate          float64
Tumor_Growth_Rate      float64
Family_History          object
MRI_Result              object
Follow_Up_Required      object
dtype: object

In [64]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Tumor_Type', 'Tumor_Size', 'Location',
       'Histology', 'Stage', 'Symptom_1', 'Symptom_2', 'Symptom_3',
       'Radiation_Treatment', 'Surgery_Performed', 'Chemotherapy',
       'Survival_Rate', 'Tumor_Growth_Rate', 'Family_History', 'MRI_Result',
       'Follow_Up_Required'],
      dtype='object')

In [65]:
df.shape

(20000, 19)

In [66]:
df.isna().sum()

Patient_ID             0
Age                    0
Gender                 0
Tumor_Type             0
Tumor_Size             0
Location               0
Histology              0
Stage                  0
Symptom_1              0
Symptom_2              0
Symptom_3              0
Radiation_Treatment    0
Surgery_Performed      0
Chemotherapy           0
Survival_Rate          0
Tumor_Growth_Rate      0
Family_History         0
MRI_Result             0
Follow_Up_Required     0
dtype: int64

In [67]:
#2. Encoding
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender']=lab.fit_transform(df['Gender'])
df['Tumor_Type']=lab.fit_transform(df['Tumor_Type'])
df['Location']=lab.fit_transform(df['Location'])
df['Histology']=lab.fit_transform(df['Histology'])
df['Stage']=lab.fit_transform(df['Stage'])
df['Symptom_1']=lab.fit_transform(df['Symptom_1'])
df['Symptom_2']=lab.fit_transform(df['Symptom_2'])
df['Symptom_3']=lab.fit_transform(df['Symptom_3'])
df['Radiation_Treatment']=lab.fit_transform(df['Radiation_Treatment'])
df['Surgery_Performed']=lab.fit_transform(df['Surgery_Performed'])
df['Chemotherapy']=lab.fit_transform(df['Chemotherapy'])
df['Family_History']=lab.fit_transform(df['Family_History'])
df['MRI_Result']=lab.fit_transform(df['MRI_Result'])
df

,Patient_ID,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1,73,1,1,5.375612,3,0,2,3,2,2,0,0,0,51.312579,0.111876,0,1,Yes
1,2,26,1,0,4.847098,2,1,1,0,0,1,1,1,1,46.373273,2.165736,1,1,Yes
2,3,31,1,0,5.588391,2,3,0,3,0,2,0,0,0,47.072221,1.884228,0,0,No
3,4,29,1,1,1.436600,3,2,3,3,2,0,1,0,1,51.853634,1.283342,1,0,No
4,5,54,0,0,2.417506,2,1,0,0,0,2,0,0,1,54.708987,2.069477,0,1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,21,1,1,9.612013,2,2,2,2,1,3,0,0,1,58.229662,0.353806,0,0,Yes
19996,19997,32,0,0,1.543560,3,3,2,0,0,3,1,1,0,77.706856,2.341074,0,1,No
19997,19998,57,0,0,3.618634,3,2,0,2,3,1,0,0,1,89.543803,2.332881,0,1,Yes
19998,19999,68,1,1,8.519086,2,1,2,2,0,3,1,1,1,83.306781,2.387202,0,1,No
19999,20000,61,1,0,9.716768,3,2,0,3,2,1,0,0,0,47.433468,2.464077,1,0,Yes

In [68]:
df.drop(['Patient_ID'],axis=1,inplace=True)
df

,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,73,1,1,5.375612,3,0,2,3,2,2,0,0,0,51.312579,0.111876,0,1,Yes
1,26,1,0,4.847098,2,1,1,0,0,1,1,1,1,46.373273,2.165736,1,1,Yes
2,31,1,0,5.588391,2,3,0,3,0,2,0,0,0,47.072221,1.884228,0,0,No
3,29,1,1,1.436600,3,2,3,3,2,0,1,0,1,51.853634,1.283342,1,0,No
4,54,0,0,2.417506,2,1,0,0,0,2,0,0,1,54.708987,2.069477,0,1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,21,1,1,9.612013,2,2,2,2,1,3,0,0,1,58.229662,0.353806,0,0,Yes
19996,32,0,0,1.543560,3,3,2,0,0,3,1,1,0,77.706856,2.341074,0,1,No
19997,57,0,0,3.618634,3,2,0,2,3,1,0,0,1,89.543803,2.332881,0,1,Yes
19998,68,1,1,8.519086,2,1,2,2,0,3,1,1,1,83.306781,2.387202,0,1,No
19999,61,1,0,9.716768,3,2,0,3,2,1,0,0,0,47.433468,2.464077,1,0,Yes

In [69]:
x=df.iloc[:,:-1]  
y=df.iloc[:,-1]

In [70]:
#Converting data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [71]:
y_train.values

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'],
      shape=(14000,), dtype=object)

In [72]:
# Normalisation
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()   #Object creation
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [73]:
#3) MODEL CREATION
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=7)
nav=GaussianNB()
sup=SVC()
lst=[knn,nav,sup]

In [74]:
for i in lst:
    print("Model name is *******************************",i)
    i.fit(x_train,y_train)
    y_pred=i.predict(x_test)
    print("Performance Evaluation is********************")
    print(confusion_matrix(y_test,y_pred))
    print('*'*100)
    print(accuracy_score(y_test,y_pred))

Model name is ******************************* KNeighborsClassifier(n_neighbors=7)
Performance Evaluation is********************
[[1463 1430]
 [1527 1580]]
****************************************************************************************************
0.5071666666666667
Model name is ******************************* GaussianNB()
Performance Evaluation is********************
[[1436 1457]
 [1589 1518]]
****************************************************************************************************
0.49233333333333335
Model name is ******************************* SVC()
Performance Evaluation is********************
[[1435 1458]
 [1523 1584]]
****************************************************************************************************
0.5031666666666667